export default function Home() {
  return (
    <main className="
      min-h-screen
      bg-gray-200
      flex
      justify-center
      p-3 sm:p-5
    ">
      <div className="
        bg-[#f3f3f3]
        w-full
        max-w-5xl
        p-5 sm:p-8 md:p-14
      ">

        {/* HEADER */}
        <div className="
          flex
          flex-col sm:flex-row
          items-center sm:items-start
          gap-4 sm:gap-6
          mb-10 sm:mb-16
        ">

          {/* LOGO */}
          <img
            src="/vrblogo.png"
            alt="VRB Logo"
            className="
              w-16 h-16
              sm:w-24 sm:h-24
              object-contain
            "
          />

          {/* TITLE */}
          <div className="flex-1 text-center">
            <h1 className="
              text-xl sm:text-3xl md:text-5xl
              font-bold
              text-blue-700
              leading-tight
            ">
              VALUERS REGISTRATION BOARD
            </h1>

            <p className="
              italic
              text-gray-600
              mt-1 sm:mt-2
              text-sm sm:text-lg
            ">
              Integrity and Fairness
            </p>
          </div>

        </div>

        {/* REGISTRATION SECTION */}
        <section className="mb-12 sm:mb-16">

          <h2 className="
            text-2xl sm:text-3xl
            font-bold
            text-blue-700
            mb-6 sm:mb-8
          ">
            REGISTRATION
          </h2>

          <div className="
            grid
            grid-cols-1 sm:grid-cols-2
            gap-y-4 sm:gap-y-5
            gap-x-6
            text-base sm:text-xl
          ">

            <p className="font-bold">Registration Number</p>
            <p>VRB/FRV/023/2019</p>

            <p className="font-bold">Name</p>
            <p>Joseph Inyas Shewiyo</p>

            <p className="font-bold">Gender</p>
            <p>Male</p>

            <p className="font-bold">Email</p>
            <p className="text-blue-700 underline break-words">
              shewiyoj@gmail.com
            </p>

            <p className="font-bold">Phone</p>
            <p>+255714814298</p>

            <p className="font-bold">Address</p>
            <p>Dodoma, Tanzania</p>

            <p className="font-bold">Registration Type</p>
            <p>Full Registration (FRV)</p>

          </div>

        </section>

        {/* EDUCATION */}
        <section className="mb-16 sm:mb-24">

          <h2 className="
            text-2xl sm:text-3xl
            font-bold
            text-blue-700
            mb-6 sm:mb-8
          ">
            EDUCATION BACKGROUND
          </h2>

          <div className="
            flex flex-col
            gap-3 sm:gap-6
            text-base sm:text-xl
          ">
            <p>
              Bachelor of Law (LLB) – The Open University Of Tanzania
            </p>

            <p>
              MSc In Land Management with Bias In Built Environment
            </p>
          </div>

        </section>

        {/* FOOTER */}
        <div className="text-base sm:text-xl">

          <div className="font-bold mb-2">
            Generated By:
          </div>

          <div className="
            flex flex-col sm:flex-row
            sm:items-center
            gap-1 sm:gap-3
          ">
            <span className="font-bold">Registrar</span>
            <span className="hidden sm:inline">:</span>
            <span>JOSEPH I. SHEWIYO</span>
          </div>

        </div>

      </div>
    </main>
  );
}