export default function Home() {
  return (
    <main className="
      min-h-screen
      bg-gray-300
      flex
      justify-center
      items-center
      p-4
    ">
      
      {/* CERTIFICATE SHELL */}
      <div className="
        bg-white
        w-full
        max-w-[900px]
        aspect-[1/1.414]  /* A4 ratio */
        shadow-2xl
        border-4
        border-blue-700
        p-6 sm:p-10
        relative
        overflow-hidden
      ">

        {/* WATERMARK (optional official feel) */}
        <div className="
          absolute
          inset-0
          flex
          items-center
          justify-center
          opacity-5
          text-6xl
          font-bold
          text-blue-700
          select-none
          pointer-events-none
        ">
          VRB
        </div>

        {/* HEADER */}
        <div className="flex items-center gap-4 mb-8 relative z-10">
          <img
            src="/vrblogo.png"
            alt="VRB Logo"
            className="w-16 h-16 sm:w-20 sm:h-20 object-contain"
          />

          <div className="flex-1 text-center">
            <h1 className="
              text-lg sm:text-3xl
              font-bold
              text-blue-800
              uppercase
              tracking-wide
            ">
              Valuers Registration Board
            </h1>

            <p className="text-xs sm:text-sm italic text-gray-600">
              Integrity and Fairness
            </p>
          </div>
        </div>

        {/* TITLE */}
        <div className="text-center mb-8 relative z-10">
          <h2 className="
            text-xl sm:text-3xl
            font-bold
            text-blue-700
            border-b-2
            border-blue-700
            inline-block
            px-4 pb-1
          ">
            REGISTRATION CERTIFICATE
          </h2>
        </div>

        {/* DETAILS */}
        <div className="grid grid-cols-2 gap-y-3 text-xs sm:text-base relative z-10">

          <span className="font-bold">Registration Number</span>
          <span>VRB/FRV/023/2019</span>

          <span className="font-bold">Name</span>
          <span>Joseph Inyas Shewiyo</span>

          <span className="font-bold">Gender</span>
          <span>Male</span>

          <span className="font-bold">Email</span>
          <span className="break-words text-blue-700">
            shewiyoj@gmail.com
          </span>

          <span className="font-bold">Phone</span>
          <span>+255714814298</span>

          <span className="font-bold">Address</span>
          <span>Dodoma, Tanzania</span>

          <span className="font-bold">Registration Type</span>
          <span>Full Registration (FRV)</span>
        </div>

        {/* EDUCATION */}
        <div className="mt-8 relative z-10">
          <h3 className="font-bold text-blue-700 mb-2">
            Education Background
          </h3>

          <p className="text-xs sm:text-base">
            Bachelor of Law (LLB) – The Open University Of Tanzania
          </p>
          <p className="text-xs sm:text-base">
            MSc In Land Management with Bias In Built Environment
          </p>
        </div>

        {/* FOOTER */}
        <div className="absolute bottom-6 left-6 right-6 flex justify-between text-xs sm:text-base relative z-10">
          <div>
            <p className="font-bold">Generated By:</p>
            <p>Registrar</p>
          </div>

          <div className="text-right">
            <p className="font-bold">Signature</p>
            <p className="mt-2">JOSEPH I. SHEWIYO</p>
          </div>
        </div>

      </div>
    </main>
  );
}