export default function Home() {

  return (

    <main className="
      min-h-screen
      bg-gray-200
      flex
      justify-center
      p-5
    ">

      <div className="
        bg-[#f3f3f3]
        w-full
        max-w-5xl
        p-8
        md:p-14
      ">

        {/* HEADER */}

        <div className="
          flex
          items-start
          gap-6
          mb-16
        ">

          {/* LOGO */}

          <img
            src="/vrblogo.png"
            alt="VRB Logo"
            className="
              w-24
              h-24
              object-contain
            "
          />

          {/* TITLE */}

          <div className="flex-1 text-center">

            <h1 className="
              text-3xl
              md:text-5xl
              font-bold
              text-blue-700
            ">
              VALUERS REGISTRATION BOARD
            </h1>

            <p className="
              italic
              text-gray-600
              mt-2
              text-lg
            ">
              Integrity and Fairness
            </p>

          </div>

        </div>

        {/* REGISTRATION SECTION */}

        <section className="mb-16">

          <h2 className="
            text-3xl
            font-bold
            text-blue-700
            mb-8
          ">
            REGISTRATION
          </h2>

          <div className="
            grid
            grid-cols-1
            md:grid-cols-2
            gap-y-5
            text-xl
          ">

            <p className="font-bold">
              Registration Number
            </p>

            <p>
              VRB/FRV/023/2019
            </p>

            <p className="font-bold">
              Name
            </p>

            <p>
              Joseph Inyas Shewiyo
            </p>

            <p className="font-bold">
              Gender
            </p>

            <p>
              Male
            </p>

            <p className="font-bold">
              Email
            </p>

            <p className="text-blue-700 underline">
              shewiyoj@gmail.com
            </p>

            <p className="font-bold">
              Phone
            </p>

            <p>
              +255714814298
            </p>

            <p className="font-bold">
              Address
            </p>

            <p>
              Dodoma, Tanzania
            </p>

            <p className="font-bold">
              Registration Type
            </p>

            <p>
              Full Registration (FRV)
            </p>

          </div>

        </section>

        {/* EDUCATION */}

        <section className="mb-24">

          <h2 className="
            text-3xl
            font-bold
            text-blue-700
            mb-8
          ">
            EDUCATION BACKGROUND
          </h2>

          <div className="
            flex
            flex-col
            gap-6
            text-xl
          ">

            <p>
              Bachelor of Law (LLB) –The Open University Of Tanzania
            </p>

            <p>
              MSc In Land Management with Bias In Built Environment
            </p>

          </div>

        </section>

        {/* FOOTER */}

        <div className="
          mt-20
          text-xl
        ">

          <div className="
            flex
            gap-3
            font-bold
          ">
            <span>Generated By:</span>
          </div>

          <div className="
            flex
            gap-6
            mt-2
          ">

            <span className="font-bold">
              Registrar
            </span>

            <span>:</span>

            <span>
              JOSEPH I. SHEWIYO
            </span>

          </div>

        </div>

      </div>

    </main>
  );
}